
# html lang
language: zh-CN

# main menu navigation
menu:
  Home: /
  Archives: /archives
  About: /about

# Miscelaneous
favicon: /favicon.ico

# stylesheets loaded in the <head>
stylesheets:
- /css/eleme-theme.css

# scripts loaded in the end of the body
scripts:
- /js/eleme-theme.js

comment: true
disqusurl: //hexo-theme.disqus.com/embed.js