
# html lang
language: zh-CN

# main menu navigation
menu:
  Home: /
  Archives: /archives
  About: /about

# Miscelaneous
favicon: /favicon.ico

# stylesheets loaded in the <head>
stylesheets:
- /css/eleme-theme.css

# scripts loaded in the end of the body
scripts:
- /js/eleme-theme.js

# set comment to true & change disqus_shortname to enable comment
comment: false
#disqus_shortname: your short name